# This sould not be done. Consider sealing the secret with Sealed Secrets
# Just for testing purposes
apiVersion: v1
data:
  username: YXBw # app
  password: cGFzc3dvcmQ= # password
kind: Secret
metadata:
  name: app-secret
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/basic-auth