apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entrypoint
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100" # Last sync
spec:
  project: default
  source:
    repoURL: https://github.com/llorenzinho/benchmark_stack.git
    targetRevision: HEAD
    path: helm/entrypoints
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true