apiVersion: v2
name: monitoring
description: Monitoring Stack Helm Chart
type: application
version: 70.4.2
appVersion: "v0.81.0"
dependencies:
- name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 70.4.2
  tags:
  - monitoring
