apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web  # Usa la porta HTTP (80)
    traefik.ingress.kubernetes.io/rule-type: PathPrefix  # Gestisci il percorso /grafana
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /argo
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80