apiVersion: v2
name: db
description: A Helm chart for Postgres
type: application
version: 0.1.0
appVersion: "1.25.1"
dependencies:
- name: cloudnative-pg
  condition: cloudnative-pg.enabled
  version: 0.23.2
  repository: https://cloudnative-pg.github.io/charts
  tags:
  - cloudnative-pg
  - db
