apiVersion: v2
name: argocd
description: A Helm chart for self managed argo cd
type: application
version: 7.8.24
appVersion: "v2.14.9"
dependencies:
- name: argo-cd
  version: 7.8.24
  repository: https://argoproj.github.io/argo-helm
