argo-cd:
  fullnameOverride: argocd
  configs:
    cm:
      server.basehref: /argocd
  dex:
    enabled: true
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  # server:
  #   extraArgs:
  #   - --insecure
